# Generated by Django 4.2.1 on 2023-06-17 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('medicines', 'Медикаменти'), ('vitamin', 'БАД і вітаміни'), ('medgoods', 'Медичний товар'), ('antibiotic', 'Антибіотики'), ('cosmetic', 'Товари для косметологів'), ('goodsformom', 'Товари для мам і дітей')], max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dp', 'Дніпро'), ('zp', 'Запоріжжя'), ('kv', 'Київ'), ('lv', 'Львів'), ('od', 'Одеса'), ('kh', 'Харків')], max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('bonus_card_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer_first_name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('testimony', models.TextField()),
                ('composition', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.TextField()),
                ('country_of_origin', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('method_of_use', models.TextField()),
                ('interaction_with_food', models.TextField()),
                ('rating', models.IntegerField()),
                ('comments', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('ready for shipment', 'Готово до відправлення'), ('delivered', 'Доставлено'), ('cancelled', 'Відмінено'), ('returned', 'Повернено')], max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(choices=[('courier', ' Кур\'єром від аптеки "Бажаємо здоров\'я" '), ('self', 'Самовивіз з аптеки'), ('np', 'Нова пошта Відділення'), ('up', 'Укрпошта Відділення')], max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Оплата карткою'), ('card', 'Оплата готівкою')], max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.city')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customer')),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.order')),
            ],
        ),
    ]
